langugae: €ý,cpp€ý,
compiler:
  - g++-9.1

git:
  depth: 3
  submodules: true

branches:
  only:
  - master
  - develop

os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=gcc-9.1 && CXX=g++-9.1"


#In case of mpi cause it interferes with these
#before_install:
#  - test -n $CC  && unset CC
#  - test -n $CXX && unset CXX
#
addons:
  sources:
    - george-edison55-precise-backports
  apt:
    packages:
      - cmake-data
      - cmake
