language: cpp
compiler:
  - gcc
  - clang
dist: trusty
git:
  depth: 3
  submodules: true

branches:
  only:
  - master
  - develop

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake CMakeLists.txt && make 
