language: cpp
compiler:
  - gcc
  - clang
dist: trusty
git:
  depth: 3
  submodules: true

branches:
  only:
  - master
  - develop

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - george-dision55-precise-backports
          packages:
            - clang-6.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake CMakeLists.txt && make 
