language: cpp
compiler:
  - gcc
  - clang

git:
  depth: 3
  submodules: true

branches:
  only:
  - master
  - develop

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - george-dision55-precise-backports
          packages:
            - clang-5.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
